const express = require('express')
const mongoose = require('mongoose')
const dbconnect = require('./db/mongoose')
const app = express()
const env = require('dotenv').config()
const port = process.env.PORT
mongoose.set('strictQuery', true)
dbconnect()
app.use(express.json())
const userRouter = require('./routers/user')
app.use(userRouter)
const adminRouter = require('./routers/admin')
app.use(adminRouter)
const productsRouter = require('./routers/products')
app.use(productsRouter)
const blogRouter = require('./routers/blog')
app.use(blogRouter)
app.listen(port, () => console.log(`server is running at port ${port}`))